### ISSUE TITLE
Contáctanos

### ISSUE THREAD

**Issue by almaosorio** [viriesc/micrositio_adip#11]
![image](https://user-images.githubusercontent.com/62679070/96192289-5892ba80-0f0b-11eb-9acd-2bb38278d7e7.png)

Poner: politicadedatos@cdmx.gob.mx

**Comment by almaosorio** [comment]
Si podemos ponerle un párrafo antes: 

"Si tienes dudas sobre la Política de Gestión de Datos, el Datálogo, las funciones de los Oficiales de Información, las obligaciones de los Entes Públicos en gestión de datos, o simplemente quieres saber cómo involucrarte, escribe un correo a politicadedatos@cdmx.gob.mx."

¡Queremos escucharte!

**Comment by viriesc** [comment]
Bueno, agregué el mismo textbox que en contactanos, no se si sea repetitivo, en el test del 26 checamos ese detalle
