### ISSUE TITLE
El título del sitio está mal

### ISSUE THREAD

**Issue by almaosorio** [viriesc/micrositio_adip#15]
Actualmente dice "Portal de la Política de Gestión de Datos de la Ciudad de México" 

Debe decir --> "Portal de la Política de Datos de la Ciudad de México"

**Comment by almaosorio** [comment]
Igual el actual footer dice: "Micrositio de Gestion de datos de la ADIP" 

Cambiar para que coincida con el título --> " Portal de la Política de Datos de la Ciudad de México"

**Comment by viriesc** [comment]
Listo, ya quedo en el landing, en el config y en el footer
