### ISSUE TITLE
En https://viriesc.github.io/micrositio_adip/marco_legal

### ISSUE THREAD

**Issue by almaosorio** [viriesc/micrositio_adip#20]
Cambiar el link de la Ley de Operación e Innoación Digitital; es necesario poner el link de Gaceta: https://data.consejeria.cdmx.gob.mx/portal_old/uploads/gacetas/17741f8b4232061a75318eb627e9951e.pdf (actualmente está este link: http://www.paot.org.mx/centro/leyes/df/pdf/2020/LEY_OPERA_INNOVA_DIGITAL_CDMX_31_12_2018.pdf)

**Comment by almaosorio** [comment]
Homologar cómo se presentan los links: 
![image](https://user-images.githubusercontent.com/62679070/98405651-3c79c900-2032-11eb-9c01-707e446339a5.png)

Mi propuesta es que en lugar de que diga "Ir al link" o algo así, que el link sea el texto. Es decir, que Ley de Operación e Innovación Digital sea un link, que Política de gestión de datos sea un link, y así.

**Comment by viriesc** [comment]
A la mejor valdría la pena agregar una descripción del documento, para que no quede un listado en verde ... pero si se me hace buena solución.

**Comment by viriesc** [comment]
Y es que si no queda en verde, cabe la duda de si es una etiqueta o es un link para el usuario. (visualmente no se entiende)
