### ISSUE TITLE
Cultura de datos está vacío

### ISSUE THREAD

**Issue by almaosorio** [viriesc/micrositio_adip#21]
![image](https://user-images.githubusercontent.com/62679070/98405955-bca02e80-2032-11eb-8d4a-8a2413567bb5.png)

**Al hacer click en "Cultura de datos" en el menú de la izquierda, te lleva a una página que está vacía. Recomiendo poner un párafo introductorio que diga:** 

<p>La cultura de datos es un componente transversal del Marco de Gestión de Datos de la Ciudad de México (link a la sección de Marco de Gestión de Datos) que se refiere al desarrollo de competencias, capacidades y habilidades que permitan comprender el valor e importancia de los datos.</p>
<br>
<p>El desarrollo de una cultura de datos es fundamental porque las personas son la pieza más importante de la implementación cualquier política. Al ser la base de la Administración Pública, las acciones del día a día de las personas moldean las prácticas e instituciones en materia de datos.</p>
<br>
<p>¡Para promoverla, estamos desarrollando distintos materiales que podrás explorar aquí!</p>

**Comment by almaosorio** [comment]
El url de cultura de datos makes no sense (quitarle lo de guías?) 
![image](https://user-images.githubusercontent.com/62679070/98407318-13a70300-2035-11eb-84df-2bace89a9574.png)

**Comment by almaosorio** [comment]
Quitar DIPLOMADO EAP

![image](https://user-images.githubusercontent.com/62679070/98407953-1f46f980-2036-11eb-96a8-857ee7186ff0.png)
![image](https://user-images.githubusercontent.com/62679070/98407972-266e0780-2036-11eb-8cba-e10d55bf937b.png)

**Comment by almaosorio** [comment]
Sidebar de Cultura de datos

-Introducción a la gestión de datos (aquí van las ppts)
-Guías prácticas (que contenga: Recomendaciones para calidad de datos en hojas de cálculo, ¿Qué es un diccionario de datos?, Uso de catálogos de datos) 
-Más materiales (que contenga: reutilización de materiales de socialtic y datatherapy)
-Glosario

**Comment by almaosorio** [comment]
Introducción a la gestión de datos-

Contenido (pedirselas a Dalila): 
Introducción a la Política de Gestión de Datos 
Introducción a los datos
Introducción a conjuntos de datos y bases de datos 
Introducción a los metadatos

**Comment by almaosorio** [comment]
Guías prácticas-

Contenido: 
Recomendaciones básicas para tener datos de calidad en hojas de cálculo
Recomendaciones para elaborar un diccionario de datos
Recomendaciones para utilizar catálogos de datos

**Comment by viriesc** [comment]
> Sidebar de Cultura de datos
> 
> -Introducción a la gestión de datos (aquí van las ppts)
> -Guías prácticas (que contenga: Recomendaciones para calidad de datos en hojas de cálculo, ¿Qué es un diccionario de datos?, Uso de catálogos de datos)
> -Más materiales (que contenga: reutilización de materiales de socialtic y datatherapy)
> -Glosario

Agregarlo? o sustituir lo que hay?
