### ISSUE TITLE
Sidebar: Marco para la Gestión de Datos

### ISSUE THREAD

**Issue by Daliliuxurius** [viriesc/micrositio_adip#38]
En el sidebar dice "Modelo de Gestión de Datos" y debe ser "Marco para la Gestión de Datos"
![image](https://user-images.githubusercontent.com/65377014/98570889-87395200-2279-11eb-8fcb-b644f5f57780.png)

**Comment by viriesc** [comment]
Sii, asi estaba en el Wireframe, pero creo que me lo corrigieron. Lo deje como Marco..,
