### ISSUE TITLE
Homologar los números en la lista desplegable de Componentes del MGD-CDMX

### ISSUE THREAD

**Issue by Daliliuxurius** [viriesc/micrositio_adip#39]
Gobernanza y cultura de datos, y Calidad de datos vienen con números romanos en minúscula. Poner todos en mayúsculas y, además, agregar un espacio entre el número y la palabra. 
![image](https://user-images.githubusercontent.com/65377014/98571844-94a30c00-227a-11eb-8afc-8da22bd264e8.png)

**Comment by mfuentesbo** [comment]
Además está mal la numeración. Dice "IV" luego "VI", después "V" y luego otra vez "VI". Deben ser del I al VIII.
