### ISSUE TITLE
acentuar "quienes" en el sidebar

### ISSUE THREAD

**Issue by almaosorio** [viriesc/micrositio_adip#4]
![image](https://user-images.githubusercontent.com/62679070/96191581-f7b6b280-0f09-11eb-95b2-a3863179c4c4.png)
 
En el sidebar > Sobre la política de gestión de datos > Quienes participan --> Le hace falta el acento a "quiénes"

Es decir de Quienes --> Quiénes

**Comment by viriesc** [comment]
Listo, una disculpa, es que tengo el teclado en inglés para desarrollar más rápido y pospusé los acentos, ya estoy checando todos de una vez.
