### ISSUE TITLE
Salto de párrafo después de un subtítulo

### ISSUE THREAD

**Issue by Daliliuxurius** [viriesc/micrositio_adip#42]
En todas las secciones, agregar un salto de párrafo después de un subtítulo, una pregunta, etc. para que se vea mejor distribuido el texto.

**Comment by viriesc** [comment]
En las pestañas verdes y grises?

**Comment by Daliliuxurius** [comment]
Por ejemplo aquí: 
![image](https://user-images.githubusercontent.com/65377014/98736284-3bb2a100-236a-11eb-8a66-c62798fd828c.png)

AUNQUE ES SOLO UNA SUGERENCIA, ES MÁS CÓMO TU VEAS MEJOR EL DISEÑO
