### ISSUE TITLE
Agregar links en sección ¿Quienes participan?

### ISSUE THREAD

**Issue by mfuentesbo** [viriesc/micrositio_adip#50]
En general faltan los links de la LOID y la Política. Además, añadir links en:
- El tercer bullet de las obligaciones donde dice Inventario de Datos (https://viriesc.github.io/micrositio_adip/datalogo)
- Consulta aquí (link al artículo de la Política) las funciones de los Oficiales de Información (y agregar punto final)
- Consulta aquí (https://viriesc.github.io/micrositio_adip/directorio/) el Directorio de Oficiales de Información

**Comment by Daliliuxurius** [comment]
El artículo de la Política donde se detallan las funciones de los OI es el: quadragésimo quinto 
Aquí el link a la Política Actualizada: http://www3.contraloriadf.gob.mx/prontuario/index.php/normativas/Template/ver_mas/68319/42/1/0
