### ISSUE TITLE
Arreglar sección "Cómo participar"

### ISSUE THREAD

**Issue by Daliliuxurius** [viriesc/micrositio_adip#61]
En la sección "cómo participar" hacer diversos cambios: 

- [x] Que en el sidebar como en el título de la sección ambos sean "Cómo participar" 

- [x] El texto introductorio a la sección debe decir: Queremos hacer la Política de Gestión de Datos lo más abierta y participativa posible, para ello hemos creado estos tres canales principales: 

- [x] Que los links aparezcan directamente abajo de la presentación a la sección y no aparte en "contenido". 

- [x] El nombre del link a "Mesas técnicas Interinstitucionales" es en plural y con mayúsculas cada palabra (actualmente está como: Mesa técnica https://viriesc.github.io/micrositio_adip/mesa_tec/ )

![image](https://user-images.githubusercontent.com/65377014/98582469-a12e6100-2288-11eb-821d-bbf511f0fd0e.png)

**Comment by mfuentesbo** [comment]
También hay que quitar el texto que dice "Proyecto en Github", para que solo quede el link como viene en contenido.

**Comment by mfuentesbo** [comment]
Y en el sidebar también hay que cambiar "Mesa técnica" por "Mesas Técnicas Interinstitucionales"
