### ISSUE TITLE
Completar info, corregir typos y agregar links en preguntas frecuentes

### ISSUE THREAD

**Issue by mfuentesbo** [viriesc/micrositio_adip#80]
- [x] En pregunta ¿Cuáles son las funciones de los oficiales de información? poner la primera "A" del punto 2 en mayúscula.

- [x] En la respuesta de la pregunta ¿Cómo se quién es la o el Oficial de Información... falta agregar link:
Aquí (https://viriesc.github.io/micrositio_adip/directorio/) puedes consultar el directorio de las Personas Oficiales de Información por Ente Público.

- [ ] En preguntas "¿Qué pasa si un Ente Público no ha designado a su oficial de información?" y "¿Dónde puedo encontrar más información sobre la designación de los Oficialde Información?" hace falta completar información.

- [ ] Decidir si "Titular" va con mayúscula o minúscula y homologar.

**Comment by viriesc** [comment]
Ya estará la info completa en el WireFrame?
